/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.grafoEjemplo;

import controlador.TDA.grafos.PaintGraph;
import controlador.TDAListas.DynamicList;
import controlador.Utiles.Utiles;
import controlador.grafosEjemplo.EscuelaDao;
import java.util.Arrays;
import javax.swing.JOptionPane;
import org.jvnet.substance.SubstanceLookAndFeel;
import vista.grafoEjemplo.tablas.ModeloTablaAdyacenciasEscuela;
import vista.utilidadesGrafo.UtilesVistaEscuela;

/**
 *
 * @author mrbingus
 */
public class FrmGrafoSubestacion extends javax.swing.JDialog {

    private EscuelaDao ed = new EscuelaDao();
    private ModeloTablaAdyacenciasEscuela modelo = new ModeloTablaAdyacenciasEscuela();

    /**
     * Creates new form FrmGrafoEscuela
     */
    public FrmGrafoSubestacion(java.awt.Frame parent, Boolean modal) {
        super(parent, modal);
        initComponents();
        limpiar();
    }

    private void mostrarMapa() throws Exception {
        UtilesVistaEscuela.crearMapaEscuela(ed.getGrafo());
        Runtime rt = Runtime.getRuntime();
        //rt.exec(new String[]{"cmd","c", "start.brave-browser -new.window-mapas/index.html"});
        Utiles.abrirNavegadorPredeterminadoWindows("mapas/index.html");
//        java.awt.Desktop.getDesktop().browse(java.net.URI.create("mapas/index.html"));
    }

    public void cargarTabla() throws Exception {

        modelo.setGrafo(ed.getGrafo());
        modelo.fireTableDataChanged();
        tblAdyacencias.setModel(modelo);
        tblAdyacencias.updateUI();

    }

    public void limpiar() {

        try {
            UtilesVistaEscuela.cargarComboEscuela(cbxOrigin);
            UtilesVistaEscuela.cargarComboEscuela(cbxDestiny);
            cargarTabla();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void guardar() {
        try {

            Integer i = JOptionPane.showConfirmDialog(null,
                    "Seguro de guardar??",
                    "Advertencia",
                    JOptionPane.OK_CANCEL_OPTION);
            if (i == JOptionPane.OK_OPTION) {

                if (ed.getGrafo() != null) {
                    ed.guardarGrafo();
                    JOptionPane.showMessageDialog(null, "Guardadazo");

                } else {
                    JOptionPane.showMessageDialog(null, "Los grafos vacion no se guardaran");

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    private void load() throws Exception {

        Integer i = JOptionPane.showConfirmDialog(null,
                "Seguro de cargar??",
                "Advertencia",
                JOptionPane.OK_CANCEL_OPTION);
        if (i == JOptionPane.OK_OPTION) {
            ed.loadGraph();
            limpiar();
        }
    }

    private void adyacencia() {
        try {
            Integer or = cbxOrigin.getSelectedIndex();
            Integer de = cbxDestiny.getSelectedIndex();

            if (or.intValue() == de.intValue()) {
                JOptionPane.showMessageDialog(null, "No se deben apuntar a si mismos");
            } else {
                Double dist = UtilesVistaEscuela.calcularDistanciaEscuelas(ed.getLista().getInfo(or),
                        ed.getLista().getInfo(de));
                ed.getGrafo().insertEdgeE(ed.getLista().getInfo(or),
                        ed.getLista().getInfo(de),
                        Utiles.redonder(dist));
            }
            limpiar();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void mostrarGrafo() throws Exception {
        PaintGraph p = new PaintGraph();
        p.updateFileEtiquetado(ed.getGrafo());
        Utiles.abrirNavegadorPredeterminadoWindows("d3/grafo.html");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdyacencias = new javax.swing.JTable();
        txtBellman = new javax.swing.JTextField();
        txtFloyd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBellman = new javax.swing.JButton();
        btnFloyd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxOrigin = new javax.swing.JComboBox<>();
        cbxDestiny = new javax.swing.JComboBox<>();
        btnAdyacencia = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMapa = new javax.swing.JButton();
        btnGrafo = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAdyacencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAdyacencias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 560, 240));

        txtBellman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBellmanActionPerformed(evt);
            }
        });
        jPanel1.add(txtBellman, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 200, 90));
        jPanel1.add(txtFloyd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 200, 90));

        jLabel1.setText("Floyd");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        jLabel2.setText("Bellman Ford");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        btnBellman.setText("Bellman");
        btnBellman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBellmanActionPerformed(evt);
            }
        });
        jPanel1.add(btnBellman, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        btnFloyd.setText("Floyd");
        btnFloyd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFloydActionPerformed(evt);
            }
        });
        jPanel1.add(btnFloyd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jLabel3.setText("MAPA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setText("GRAFO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        cbxOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxOrigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 200, -1));

        cbxDestiny.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxDestiny, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 200, -1));

        btnAdyacencia.setText("ADYACENCIA");
        btnAdyacencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdyacenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdyacencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel5.setText("ORIGEN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel6.setText("DESTINO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        btnMapa.setText("MAPA");
        btnMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        btnGrafo.setText("GRAFO");
        btnGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        btnCargar.setText("CARGAR");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdyacenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdyacenciaActionPerformed
        // TODO add your handling code here:
        try {
            adyacencia();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAdyacenciaActionPerformed

    private void txtBellmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBellmanActionPerformed
        
    }//GEN-LAST:event_txtBellmanActionPerformed

    private void btnBellmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBellmanActionPerformed
         try {
        DynamicList<DynamicList<Double>> recorridos = new DynamicList<>();
        for (int i = 0; i < ed.getGrafo().getNum_vertice(); i++) {
            DynamicList<Double> recorrido = ed.getGrafo().bellmanFord(i);
            recorridos.add(recorrido);
        }
        
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < recorridos.getLenght(); i++) {
            sb.append("Desde el nodo ").append(i).append(": ").append(Arrays.toString(recorridos.get(i).toArray())).append("\n");
        }
        txtBellman.setText(sb.toString());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_btnBellmanActionPerformed

    private void btnFloydActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFloydActionPerformed
        try {
        DynamicList<DynamicList<Double>> distancias = ed.getGrafo().floydWarshall();

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < distancias.getLenght(); i++) {
            sb.append("Desde el nodo ").append(i).append(": ").append(Arrays.toString(distancias.get(i).toArray())).append("\n");
        }
        txtFloyd.setText(sb.toString());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_btnFloydActionPerformed

    private void btnMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapaActionPerformed
        // TODO add your handling code here:
        try {
            mostrarMapa();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnMapaActionPerformed

    private void btnGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafoActionPerformed
        try {
            mostrarGrafo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_btnGrafoActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
         // TODO add your handling code here:
        try {
            load();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            guardar();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGrafoSubestacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGrafoSubestacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGrafoSubestacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGrafoSubestacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setDefaultLookAndFeelDecorated(true);
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.DustSkin");
                new FrmGrafoSubestacion(null, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdyacencia;
    private javax.swing.JButton btnBellman;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnFloyd;
    private javax.swing.JButton btnGrafo;
    private javax.swing.JButton btnMapa;
    private javax.swing.JComboBox<String> cbxDestiny;
    private javax.swing.JComboBox<String> cbxOrigin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAdyacencias;
    private javax.swing.JTextField txtBellman;
    private javax.swing.JTextField txtFloyd;
    // End of variables declaration//GEN-END:variables
}
