/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.grafoEjemplo;

import controlador.Utiles.Utiles;
import controlador.grafosEjemplo.EscuelaDao;
import java.io.File;
import java.util.UUID;
import static javax.swing.JDialog.setDefaultLookAndFeelDecorated;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jvnet.substance.SubstanceLookAndFeel;
import vista.grafoEjemplo.tablas.ModeloTablaEscuela;

/**
 *
 * @author mrbingus
 */
public class FrmSubestacion extends javax.swing.JFrame {

    ModeloTablaEscuela modelo = new ModeloTablaEscuela();
    EscuelaDao dao = new EscuelaDao();

    private File fportada;
    private File fescudo;

    private EscuelaDao ed = new EscuelaDao();

    public FrmSubestacion() {
        initComponents();
        limpiar();
    }

    public void cargarTabla() {
        modelo.setLista(dao.getLista());
        tbl.setModel(modelo);
        tbl.updateUI();

    }

    private File cargarImagen() {
        File obj = null;
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter
                = new FileNameExtensionFilter("Imagenes", "jpg", "png", "jpeg");
        chooser.addChoosableFileFilter(filter);
        Integer resp = chooser.showOpenDialog(this);
//        if (resp == JFileChooser.APPROVE_OPTION) {
        obj = chooser.getSelectedFile();
//            System.out.println("Ta bien" + obj.getName());
//        } else {
//            System.out.println("no jala");
//        }
        return obj;
    }

    public void limpiar() {
        txtEscudo.setText("");
        txtLatitud.setText("");
        txtLongitud.setText("");
        txtNombre.setText("");
        txtPortada.setText("");
        cargarTabla();
    }

    private Boolean verificar() {

        return !(txtEscudo.getText().trim().isEmpty()
                && txtLatitud.getText().trim().isEmpty()
                && txtLongitud.getText().trim().isEmpty()
                && txtNombre.getText().trim().isEmpty()
                && txtPortada.getText().trim().isEmpty());
    }

    private void guardarEscuela() {
        if (verificar()) {
            ed.getEscuela().setNombre(txtNombre.getText());
            ed.getEscuela().getCoordenadas().setLatiitud(Double.parseDouble(txtLatitud.getText()));
            ed.getEscuela().getCoordenadas().setLongitud(Double.parseDouble(txtLongitud.getText()));
            String nEscudo = UUID.randomUUID().toString();
            String nPortada = UUID.randomUUID().toString();
            String nombreaux = "foto" + nEscudo + "." + Utiles.extension(fescudo.getName());
            try {
                Utiles.copiarArchivo(fescudo, new File(nombreaux));
                nombreaux = "foto" + nPortada + "." + Utiles.extension(fportada.getName());
                Utiles.copiarArchivo(fportada, new File(nombreaux));
            } catch (Exception e) {
            }

            ed.getEscuela().setLogo("foto" + nEscudo + "." + Utiles.extension(fescudo.getName()));
            ed.getEscuela().setLugar("foto" + nPortada + "." + Utiles.extension(fportada.getName()));

            if (ed.persist()) {
                JOptionPane.showMessageDialog(null, "Guardado Exitoso");
            } else {
                JOptionPane.showMessageDialog(null, "Guardado Incorrecto");
            }
            ed.setEscuela(null);
            limpiar();
            nEscudo = null;
            nPortada = null;
            nombreaux = null;
        } else {
            JOptionPane.showMessageDialog(null, "Llena todos los campos");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtEscudo = new javax.swing.JTextField();
        txtPortada = new javax.swing.JTextField();
        txtLongitud = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtLatitud = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 30));

        txtEscudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEscudoMouseClicked(evt);
            }
        });
        getContentPane().add(txtEscudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, 30));

        txtPortada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPortadaMouseClicked(evt);
            }
        });
        txtPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortadaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 170, 30));
        getContentPane().add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 170, 30));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 620, 200));
        getContentPane().add(txtLatitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 170, 30));

        jLabel1.setText("LATITUD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setText("LOGO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel4.setText("LUGAR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel5.setText("LONGITUD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jButton1.setText("CARGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jButton2.setText("CARGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jButton3.setText("GUARDAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortadaActionPerformed
        try {
            fportada = cargarImagen();
            if (txtPortada != null) {
                txtPortada.setText(fportada.getAbsolutePath());
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR);
        }
    }//GEN-LAST:event_txtPortadaActionPerformed

    private void txtEscudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEscudoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() >= 2) {
            new FrmFoto(null, true, fescudo).setVisible(true);

        }
    }//GEN-LAST:event_txtEscudoMouseClicked

    private void txtPortadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPortadaMouseClicked
        if (evt.getClickCount() >= 2) {
            new FrmFoto(null, true, fportada).setVisible(true);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortadaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
        try {
            fescudo = cargarImagen();
            if (txtEscudo != null) {
                txtEscudo.setText(fescudo.getAbsolutePath());
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            fportada = cargarImagen();
            if (txtPortada != null) {
                txtPortada.setText(fportada.getAbsolutePath());
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e.getMessage(), "Error", ERROR);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            guardarEscuela();
        } catch (Exception e) {
            System.out.println(e.getMessage() + "  en el guardado");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSubestacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSubestacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSubestacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSubestacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setDefaultLookAndFeelDecorated(true);
                SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.DustSkin");
                new FrmSubestacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtEscudo;
    private javax.swing.JTextField txtLatitud;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPortada;
    // End of variables declaration//GEN-END:variables
}
